apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: mini-ecommerce
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded "postgres" (echo -n "postgres" | base64)
  POSTGRES_PASSWORD: dGVzdHBhc3M= # base64 encoded "testpass"
  POSTGRES_DB: bWluaV9lY29tbWVyY2U= # base64 encoded "mini_ecommerce"