apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: mini-ecommerce
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: YWRtaW4= # base64 encoded "admin" (echo -n "admin" | base64)
  RABBITMQ_DEFAULT_PASS: cGFzcw== # base64 encoded "pass"
